sonar.projectKey=sonar-python-test
sonar.projectName=sonar-python-test
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=python
sonar.python.version=3

sonar.host.url=https://6310-197-47-51-91.ngrok-free.app
sonar.token=squ_33ed8fbb6f0dbb80127862754fba3ea9c15c3084
